backend:
  name: github
  repo: chaichuk/tesla_begginer_FAQ
  branch: main
  auth_type: pkce
  app_id: Ov23li2sT0GtlXGyLpso
  open_authoring: true
  
publish_mode: editorial_workflow

media_folder: "docs/assets"
public_folder: "assets"

collections:
  - name: "pages"
    label: "Сторінки Wiki"
    folder: "docs"
    create: true
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Текст сторінки", name: "body", widget: "markdown"}
